name: todo_app
description: A new Flutter project with Clean Architecture by Abdalluh Essam
# Flutter version on machine: 3.29.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  dio:
  shared_preferences: ^2.5.3
  easy_localization: ^3.0.7+1
  intl: ^0.19.0
  equatable:
  get_it:
  cached_network_image:
  flutter_screenutil: ^5.9.3
  flutter_animate:
  freezed_annotation:
  json_annotation:
  flutter_native_splash: ^2.4.6
  animate_do:
  lottie:
  google_fonts:
  flutter_launcher_icons:
  animator:
  dartz:
  flutter_svg:
  cupertino_icons:
  bloc: ^9.0.0
  table_calendar: ^3.1.3
  sqflite: ^2.4.2
  persistent_bottom_nav_bar_v2: ^5.3.1
  local_auth: ^2.3.0
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  json_serializable:
  bloc_test:
  mockito:
  flutter_lints:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/lang/
